trigger:
- azpipe

resources:
- repo: self

pool:
 vmImage: 'ubuntu-latest'


stages:
- stage: Build and Push
  displayName: Build
  jobs:
  - job: BuildPush
    steps:
    - task: Docker@2
      name: BuildAndPush
      inputs:
        containerRegistry: 'azpipecr'
        repository: 'azcr'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
