trigger:
- azpipe

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  
  jobs:
  - job: Build
    displayName: Build job 
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'azpipecr'
        repository: 'azcr'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(tag)