trigger:
- azpipe

resources:
- repo: self

pool:
 vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build and Push
  displayName: Build and Push image
  jobs:
  - job: BuildPush
    displayName: Build and Push Images 
    steps:
    - task: Docker@2
      displayName: Build and Push an image
      inputs:
        containerRegistry: 'azpipecr'
        repository: 'azcr'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
