trigger:
- oc

variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'azpipecr'
  repository: 'azcr'
  ResourceGroup: 'azpipe'
  Subscription: 'Visual Studio Enterprise Subscription – MPN(d1b305c5-2c51-4f0a-a6b8-04e9fe0d8c17)'
pool:
     vmImage: 'ubuntu-latest'
stages:
- stage: oc
  displayName: OC Verfied
  jobs:
  - job: oc 
    displayName: OC Login  
    steps:
    - task: oc-cmd@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'openshift'
        cmd: 'oc whoami'
    - task: oc-cmd@2
      inputs:
        connectionType: 'OpenShift Connection Service'
        openshiftService: 'openshift'
        cmd: 'oc get sa'
