trigger:
- azpipe

variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'azpipecr'
  repository: 'azcr'
  ResourceGroup: 'azpipe'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: DotNet 
    displayName: DotNet Build and Test
    pool:
     vmImage: 'windows-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: 'Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj'
        feedsToUse: 'select'
  - job: Docker
    displayName: Build And Push Docker job 
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: $(containerRegistry)
        repository: $(repository)
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: $(tag)
  
