trigger:
- azpipe

variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'azpipecr'
  repository: 'azcr'
  ResourceGroup: 'azpipe'
  Subscription: 'Visual Studio Enterprise Subscription – MPN(d1b305c5-2c51-4f0a-a6b8-04e9fe0d8c17)'
pool:
     vmImage: 'windows-latest'
stages:
- stage: Dotnet_Stage
  displayName: Build and push stage
  jobs:
  - job: DotNet 
    displayName: DotNet Build and Test   
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: 'Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj'
        arguments: '-c Release -o $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/After/build'
        zipAfterPublish: false
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: 'Tailspin.SpaceGame.Web/*.csproj'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '-c Release -o $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/After/publish'
        zipAfterPublish: false

#    - task: CmdLine@2
#      inputs:
#        script: 'DIR $(Build.SourcesDirectory) && DIR $(Build.SourcesDirectory)\Tailspin.SpaceGame.Web\After &&  DIR $(Build.SourcesDirectory)\chart\ '

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: $(containerRegistry)
        repository: $(repository)
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: $(tag)
    - task: HelmInstaller@0
      inputs:
        helmVersion: '2.14.1'
        installKubectl: true
    - task: CmdLine@2
      inputs:
        script: 'DIR $(Build.SourcesDirectory)  && DIR $(Build.SourcesDirectory)\chart\ '
    - task: HelmDeploy@0
      inputs:
        azureContainerRegistry: $(containerRegistry)
        azureResourceGroupForACR: $(ResourceGroup)
        azureSubscriptionForACR: $(Subscription)
        command: 'package'
        chartPath: $(Build.SourcesDirectory)/chart/dotnet/
        destination: $(Build.ArtifactStagingDirectory)/DeployCharts/gzipped/
        arguments: '--app-version $(Build.BuildId)'
        failOnStderr: true
    - task: CmdLine@2
      inputs:
        script: 'DIR $(Build.ArtifactStagingDirectory)\DeployCharts\gzipped\ '
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/DeployCharts/gzipped'
        ArtifactName: 'helm'
        
  
